import type { Metadata } from "next";
import "./globals.css";
import { Roboto, Roboto_Slab } from "next/font/google";
const roboto = Roboto_Slab({
  weight: "500",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
